runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: bavarder.app
- url: /settings
  script: bavarder.app
- url: /material.css
  static_files: stylesheets/material.css
  upload: stylesheets/material.css
- url: /manifest.webmanifest
  static_files: static/manifest.webmanifest
  upload: static/manifest.webmanifest
- url: /icon-512.png
  static_files: static/icon-512.png
  upload: static/icon-512.png
- url: /bavarder.js
  static_files: scripts/bavarder.js
  upload: scripts/bavarder.js
- url: /sw.js
  static_files: scripts/sw.js
  upload: scripts/sw.js
- url: /msgscreen.js
  static_files: scripts/msgscreen.js
  upload: scripts/msgscreen.js
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico