runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: bavarder.app
- url: /changesetting
  script: bavarder.app
- url: /sendmsg
  script: bavarder.app
- url: /makeuser
  script: bavarder.app
- url: /user
  script: bavarder.app
- url: /rscvmsgs
  script: bavarder.app
- url: /delprof
  script: bavarder.app
- url: /associateprof
  script: bavarder.app
- url: /firebase-messaging-sw.js
  static_files: scripts/firebase-messaging-sw.js
  upload: scripts/firebase-messaging-sw.js
- url: /material.css
  static_files: stylesheets/material.css
  upload: stylesheets/material.css
- url: /toggle-md.css
  static_files: stylesheets/toggle-md.css
  upload: stylesheets/toggle-md.css
- url: /manifest.webmanifest
  static_files: static/manifest.webmanifest
  upload: static/manifest.webmanifest
- url: /icon-512.png
  static_files: static/icon-512.png
  upload: static/icon-512.png
- url: /bavarder.js
  static_files: scripts/bavarder.js
  upload: scripts/bavarder.js
- url: /sw.js
  static_files: scripts/sw.js
  upload: scripts/sw.js
- url: /msgscreen.js
  static_files: scripts/msgscreen.js
  upload: scripts/msgscreen.js
- url: /settings.js
  static_files: scripts/settings.js
  upload: scripts/settings.js
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /notificon.ico
  static_files: static/notificon.ico
  upload: static/notificon.ico