runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: bavarder.app
- url: /material.css
  static_files: stylesheets/material.css
  upload: stylesheets/material.css
- url: /manifest.webmanifest
  static_files: static/manifest.webmanifest
  upload: static/manifest.webmanifest